name: customer_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  cupertino_icons: ^1.0.8
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  geodesy: ^0.10.2
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.3
  file_saver: ^0.2.12
  google_fonts: ^6.2.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.4"


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#f06a04"
    theme_color: "#f06a04"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"

# This section forces the use of newer packages to fix build errors.
dependency_overrides:
  geolocator: ^12.0.0
  geolocator_android: 4.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/customer_app_logo_.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg