// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA4Ccq31568ER2HKmD8LSR0V-YRmqotrI',
    appId: '1:7129513406:web:f99672790dfa5628e74def',
    messagingSenderId: '7129513406',
    projectId: 'biryani-break',
    authDomain: 'biryani-break.firebaseapp.com',
    storageBucket: 'biryani-break.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsRGZnbSjJKKrueG5hxZg_JCzS_-nlKDA',
    appId: '1:7129513406:android:d8c5b4c94fbc9008e74def',
    messagingSenderId: '7129513406',
    projectId: 'biryani-break',
    storageBucket: 'biryani-break.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7XQO5y0pavJAANV3f7xM0Vq8dC1Mz8o0',
    appId: '1:7129513406:ios:43ed5965a5194c6fe74def',
    messagingSenderId: '7129513406',
    projectId: 'biryani-break',
    storageBucket: 'biryani-break.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

}